apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eshop
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/vigregus/eshop.git
    targetRevision: HEAD
    #username: vigregus
    #password: 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
    path: release
  destination: 
    server: https://kubernetes.default.svc
    namespace: eshop

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
