apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eshop
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/vigregus/eshop.git
    targetRevision: HEAD
    path: release
  destination: 
    server: https://kubernetes.default.svc
    namespace: eshop

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
